### ISSUE TITLE
Times are wrong?

### ISSUE THREAD

**Issue by Ap0logize** [bigfoott/ScrapedDuck#10]
It seems to not add the events (Community day) in Local Time to my calendar. The Community day is 2 PM - 5 PM local time, but it adds the April community day to 8-11 PM into my google calendar

**Comment by Anna-28** [comment]
Seems fine for me, this may be an issue with the google calendar import not using local time rather than ScrapedDuck's api.

**Comment by bigfoott** [comment]
Hi! The DateTime data available here is pulled directly from LeekDuck.

You may be looking for the go-calendar project. If you're still encountering time issues with it I'd open an issue here: https://github.com/othyn/go-calendar
