### ISSUE TITLE
<br> shows up in Community day disclaimer

### ISSUE THREAD

**Issue by Anna-28** [bigfoott/ScrapedDuck#11]
A recent change to the format of the community day pages added HTML line breaks here.

They probably should be stripped by ScrapedDuck as the data already includes `\n` in it.

```json
"bonusDisclaimers": [
  "* While most bonuses are only active during the three hours of the event, these bonuses will be active from 2:00 p.m. to 10:00 p.m. local time.<br>\n** The three-hour Incense bonus excludes Daily Adventure Incense.<br>\n*** The three-hour lure bonus excludes Golden Lure Modules."
],
```

Perhaps each disclaimer should also be their own entry in the `bonsuDisclaimers` array, rather than having `\n`.

**Comment by bigfoott** [comment]
Thanks for the heads up! This should be fixed in https://github.com/bigfoott/ScrapedDuck/commit/09f2e35285567b4581cedf784375f64db4786229.
