### ISSUE TITLE
Buddy & Friendship tasks missing "type"

### ISSUE THREAD

**Issue by Anna-28** [bigfoott/ScrapedDuck#12]
https://raw.githubusercontent.com/bigfoott/ScrapedDuck/data/research.json

tasks for the Buddy & Friendship category are missing a "type".

**Comment by bigfoott** [comment]
Silly bug on my end, should be fixed in https://github.com/bigfoott/ScrapedDuck/commit/bd2ebf08de2287e7f44537e91ef8356cbd8710a3, thanks!
