### ISSUE TITLE
Community Day extraData: bonuses doesn't pull disclaimer

### ISSUE THREAD

**Issue by lostcat420** [bigfoott/ScrapedDuck#2]
The bonuses data for the Community Day event show the asterisk for the disclaimer at the bottom of the bonuses, but the extraData doesn't pull the disclaimer itself
Disclaimer:

> * While most bonuses are only active during the three hours of the event, these bonuses will be active from 11:00 a.m. to 7:00 p.m. local time.

Side note: I'm working on an iOS shortcut to quick reference some of this data. Leek Duck pointed me to this repo. I'd love to share progress with you. Let me know how to best contact you.

**Comment by bigfoott** [comment]
Hi! Sorry for the delayed response. I'll take a look into this when I get a chance (preferrably before the actual community day lol), been fairly busy lately.

And as for the shortcut, hit me up on twitter [@bigfoootttt](https://twitter.com/bigfoootttt) and I'll follow back so we can DM, sounds cool!

**Comment by bigfoott** [comment]
Sorry, I haven't had a chance to try to get this to work. Though from looking at the page itself it may be difficult to implement. Will likely see if I can get it to work later tonight, though it may not be out in time for Comm day unfortunately.

**Comment by bigfoott** [comment]
Hey, sorry this took so long. This has been fixed/added in d11ca6e.

I can't guarantee it'll work for the next Comm day, but I'll keep my eye on the event page once it's announced and information is available.

Thanks again for reporting this! Hope it's useful :)
