### ISSUE TITLE
Thank you and usage notification

### ISSUE THREAD

**Issue by othyn** [bigfoott/ScrapedDuck#4]
A massive thank you for this project and having it auto maintained!

I just came to do a pet project I've been meaning to get around to for a while, which is an automated iCal calendar feed of the events page:

https://gocalendar.info/
https://othyn.github.io/go-calendar/
https://github.com/othyn/go-calendar

The events JSON resource came in perfectly for this and made a few days job into only a few short hours, massive thank you! Superb project.

**Comment by bigfoott** [comment]
Wow, absolutely beautifully done. I've seen a few people mention wanting a calendar version of the widget I made, so this looks like it fits the bill perfectly. I'd post to r/TheSilphRoad and/or r/PokemonGO, I'm sure many people would find it useful :)

I'm also going to potentially add a section to the readme here listing out notable projects that use ScrapedDuck, so I'll add yours in for sure when I get around to it. Fantastic job!!

**Comment by othyn** [comment]
Thank you, very kind! It is indeed why I embarked on such a thing haha maintaining a personal calendar was getting tedious, and it looked like the community was having the same problem, went on the hunt for a nice data feed and your repo was the diamond in the rough!

Thank you! I've posted it on r/PokemonGO but it didn't get any traction - may try again in a few days or so, held off posting on r/TheSilphRoad for now, some mods can be touchy about posting all in one go 🙄

Nice one 🙌 I saw you migrated the docs over to the wiki, nice change.

**Comment by bigfoott** [comment]
Of course! Makes me feel good to know this random thing I made is useful to others :)

Yeah, reddit can be hit or miss lol. I would definitely try r/TheSilphRoad, my post for PoGOEvents/ScrapedDuck got the most eyes on it there.

And thanks! Been meaning to clean it up a bit, figured the wiki was the best spot for it.

**Comment by othyn** [comment]
> And thanks! Been meaning to clean it up a bit, figured the wiki was the best spot for it.

Good choice - and it looks really good, thank you! Also adds the benefit of keeping the URL's more consistent.

Ended up doing a post on r/TheSilphRoad and it did get more traction, people seem pleased and also raised a few bugs haha, no battling with timezones for local time...

> Makes me feel good to know this random thing I made is useful to others :)

It very much does feel nice to provide something the community enjoys and makes good use of! Primarily why I enjoy OSS dev so much, it feels nice giving back to the community.

**Comment by bigfoott** [comment]
Glad to see it got some more attention! And of course lol, timezones are always fun. The amount of time I spent specifically on getting times to show up correctly in ScrapedDuck is depressing lol (especially when you account for the fact that I get that info in an infinitely easier way now lol) 

> It very much does feel nice to provide something the community enjoys and makes good use of! Primarily why I enjoy OSS dev so much, it feels nice giving back to the community.

1 million percent agree :)
