### ISSUE TITLE
Duplicate pokemon encounters in research have same task instead of different

### ISSUE THREAD

**Issue by Anna-28** [bigfoott/ScrapedDuck#7]
This occurs with Eevee and Onix currently in March's research.
Eevee is a reward for "Evolve a Pokémon" **and** "Catch 5 Pokémon", but the json returned by ScrapedDuck for research shows two Eevee rewards for just "Evolve a Pokémon" and no mention of "Catch 5 Pokémon".

```json
    {
        "text": "Evolve a Pokémon",
        "type": "power",
        "rewards": [
            {
                "name": "Eevee",
                "image": "https://undefined",
                "canBeShiny": true,
                "combatPower": {
                    "min": 424,
                    "max": 459
                }
            },
            {
                "name": "Eevee",
                "image": "https://undefined",
                "canBeShiny": true,
                "combatPower": {
                    "min": 424,
                    "max": 459
                }
            }
        ]
    },
```

The same happens for Onix with "Battle in GO Battle League" and "Make 3 Great Throws in a row".

https://leekduck.com/research/

https://raw.githubusercontent.com/bigfoott/ScrapedDuck/data/research.json

**Comment by bigfoott** [comment]
Hi! I don't see this issue currently as I'm late to this. Will close this for now, let me know if you encounter this anywhere else in the research endpoint.

**Comment by Anna-28** [comment]
The research just recently changed for this new month.

This now occurs with Beldum and "Hatch 2 Eggs" as one of the quests.

**Comment by bigfoott** [comment]
Fixed in https://github.com/bigfoott/ScrapedDuck/commit/d2b0a0f9e246dea72d58353c70f4f5564b87433f, thanks!
