### ISSUE TITLE
Snapshot research tasks have different types

### ISSUE THREAD

**Issue by Anna-28** [bigfoott/ScrapedDuck#8]
"Take 3 snapshots of wild Water-type Pokémon" has the type "catch",
But "Take a snapshot of a wild Pokémon" has the type "misc".

Both should likely be "misc".

**Comment by bigfoott** [comment]
Hi! I know I'm late to this - at the moment this doesn't seem to be the case. It may have been an issue of the task being labelled incorrectly on the site itself.

Will close this for now, if you encounter this again let me know!
